services:
  db:
    build:
      context: .   # Carpeta donde est√° Dockerfile
      dockerfile: Dockerfile
    container_name: db_angel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  customers-api:
    build: ./customers-api
    container_name: customers-api
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=DBANGEL
      - JWT_SECRET=xyz 
      - ADMIN_USER=admin@example.com
      - ADMIN_PASS=admin123
    depends_on:
      - db  

  orders-api:
    build: ./orders-api
    container_name: orders-api
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=DBANGEL
      - JWT_SECRET=xyz 
      - CUSTOMERS_API_BASE=http://customers-api:3001
      - CUSTOMERS_API_USER=admin@example.com
      - CUSTOMERS_API_PASSWORD=admin123
    depends_on:
      - db    


volumes:
  db_data:

